[package]
name = "fawn_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
fawn_common = { path = "../fawn_common" }
serde         = { version = "1", features = ["derive"] }
serde_json    = "1"
anyhow        = "1"