[package]
name = "fawn_common"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11"
prost = "0.12"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"

[build-dependencies]
tonic-build = "0.11"
