[package]
name = "fawn_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
fawn_common = { path = "../fawn_common" }
tonic = "0.11"
tokio = { version = "1.45.0", features = ["full"] }
async-trait = "0.1"
