[package]
name = "fawn_logstore"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.5"
crc32fast = "1" # CRC-32C checksum
sha2      = "0.10"    # SHA-256 for hash32
byteorder = "1"       # handy LE helpers